services:
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n-educativo
    restart: unless-stopped
    ports:
      - "${N8N_PORT:-5678}:5678"
    environment:
      - GENERIC_TIMEZONE=${TIMEZONE:-Europe/Madrid}
      - TZ=${TIMEZONE:-Europe/Madrid}
      - N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS=true
      - N8N_RUNNERS_ENABLED=true
      - N8N_DIAGNOSTICS_ENABLED=false
      - N8N_TEMPLATES_ENABLED=true
    volumes:
      - ./n8n-data:/home/node/.n8n
